### PR TITLE
Fix minor text formatting issue

### PR DESCRIPTION
**Pull request by Kipre**

### CODE REVIEW

**Comment by urld** [comment]
Thanks for your PR. What does the output look like in your environment with this change?
For me the spacing seems to be correct already:
```
Passphrase copied to clipboard!
Clipboard will be erased in 15 seconds.

...............
```
With your change i get double spaces:
```
Passphrase copied to clipboard!
Clipboard will be erased in  15  seconds.

...............

```

**Comment by Kipre** [comment]
Indeed, I'm running on Windows, I'll admit I haven't checked the results of this change, but for me, running the latest released version does output the string without the required spaces around the number. I will check this next week and try to understand what's happening.
Anyways, thanks for the very useful tool.

**Comment by urld** [comment]
Should be fixed in https://github.com/urld/passmgr/releases/tag/v1.1.1

My old workaround for winows newline printing used fmt.Print instead of fmt.Println which seems to handle spaces between arguments differently. But cmd.exe seems to be able to print unix newlines correctly nowadays, so the workaround was no longer needed.

**Comment by Kipre** [comment]
Thanks a lot !

**Pull request closed without merging**
